### ISSUE TITLE
[POLL] Shall we squash, rebase, or merge?

### ISSUE THREAD

**Issue by flagxor** [google/wwwbasic#17]
Hi All,

Prior practice on various OSS made me instinctively squash the first commit set from a contributor.
Chromium and others do this sort of thing, but there's one major downside, github doesn't really work as well with a rebase & squash.

See here for the basic differences:
https://help.github.com/articles/about-merge-methods-on-github/

Given this has already lead to confusion: https://github.com/google/wwwbasic/pull/13/
I'm now wondering if for wwwbasic we should go with merges?

PROs:
* Github's ui, particularly around pull requests will handle things more smoothly. Folks will be kind of unhappy if they don't use the command line.
* History will have everything.

CONs:
* History will have everything. Major reason big projects sometimes like squash / rebase is that you end up with a single commit chain with large (post review) single changes.

What do folks think?
For now I'll play it by ear, but probably should figure this out.

-BradN

**Comment by metaa** [comment]
My thoughts on that:

# Rebasing
I personally prefer to have a complete (but carefully chunked) history of the first few important steps.
If you're really going to rebase, better do that as soon as possible (preferrably before there are forks), otherwise it will mess up everyone's fork.

I can't say if it's too late for it, but the sooner the better.

# Squash merging
One thing you could do is to include the initial history as a `dev` branch and treat the initial commit as a squash merge from that branch.
That way we could have the history of the first commit but don't mess up the master branch.

**Comment by FellippeHeitor** [comment]
I'm used to granular commits so that it's easier to identify faulty ones later one down the road, which makes me lean towards merge, but I'm ok with either model.

**Comment by damieng** [comment]
I normally default to merge unless squash or rebase makes it clearer.

Squash can make things clearer if somebody was trying a bunch of different things and the final piece of work makes sense as one logical piece of work and there's nothing to be gained from the intermediate commits.

**Comment by flagxor** [comment]
Seems like merge is looking favored. Let's give that a try for the time being.

A dev branch might make sense, but given we've got some varying levels of experience, I worry that'll be even more challenge for folks to grok how to prepare something.

Nothing stop someone from squashing / rebasing in their own PR, but I think for now I won't push squash/rebase if they haven't done it themselves.

Thanks all!
